// This file will (eventually) be automatically generated by the goi18n command.
package main

import (
	"github.com/nicksnyder/go-i18n/src/pkg/i18n"
)

func init() {
	i18n.AddTranslation("es_ES", "This message is displayed when the program begins", "Hello world!", "¡Hola, mundo!")
	i18n.AddTranslation("es_ES", "This message is displayed when the program ends", "Goodbye world.", "Adiós mundo")
}
