// This file will (eventually) be automatically generated by the goi18n command.
package main

import (
	"github.com/nicksnyder/go-i18n/src/pkg/i18n"
)

func init() {
	i18n.AddTranslation("es_ES", "Hello world!", "This message is displayed when the program begins", "¡Hola, mundo!")
	i18n.AddTranslation("es_ES", "Goodbye world.", "This message is displayed when the program ends", "Adiós mundo")
}
